insert into Stadium values ("Tokyo Dome", "Address 1");
insert into Stadium values ("Hiroshima Dome", "Address 2");
insert into Stadium values ("Kobe Dome", "Address 3");
insert into Stadium values ("Saitama Field", "Address 4");
insert into Stadium values ("Shinjuku Field", "Address 5");
insert into Stadium values ("Enoshima Park", "Address 6");
insert into Stadium values ("Tanaka Field", "Address 7");
insert into Stadium values ("Shinitai Dome", "Address 8");
insert into Stadium values ("Koroshite Park", "Address 9");
insert into Stadium values ("Dameda Field", "Address 10");
insert into Stadium values ("Kore Daikirai Park", "Address 11");
insert into Stadium values ("Owaridana Field", "Address 12");