insert into Stadium ("Tokyo Dome", "Address 1");
insert into Stadium ("Hiroshima Dome", "Address 2");
insert into Stadium ("Kobe Dome", "Address 3");
insert into Stadium ("Saitama Field", "Address 4");
insert into Stadium ("Shinjuku Field", "Address 5");
insert into Stadium ("Enoshima Park", "Address 6");
insert into Stadium ("Tanaka Field", "Address 7");
insert into Stadium ("Shinitai Dome", "Address 8");
insert into Stadium ("Koroshite Park", "Address 9");
insert into Stadium ("Dameda Field", "Address 10");
insert into Stadium ("Kore Daikirai Park", "Address 11");
insert into Stadium ("Owaridana Field", "Address 12");