insert into Team values (0, "Ducks", "Tokyo Dome", 0);
insert into Team values (1, "Bobcats", "Hiroshima Dome", 0);
insert into Team values (2, "Cougars", "Kobe Dome", 0);
insert into Team values (3, "Donkeys", "Saitama Field", 0);
insert into Team values (4, "Elephants", "Shinjuku Field", 0);
insert into Team values (5, "Carps", "Enoshima Park", 0);
insert into Team values (6, "Jaguars", "Tanaka Field", 1);
insert into Team values (7, "Fighters", "Shinitai Dome", 1);
insert into Team values (8, "Giants", "Koroshite Park", 1);
insert into Team values (9, "Hawks", "Dameda Field", 1);
insert into Team values (10, "Marines", "Kore Daikirai Park", 1);
insert into Team values (11, "Baystars", "Owaridana Field", 1);